# Generated by Django 5.2.6 on 2025-09-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TollRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('car', 'Car'), ('bolan', 'Bolan')], max_length=10, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
