# Generated by Django 5.2.6 on 2025-09-22 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('car', 'Car'), ('bolan', 'Bolan')], max_length=10)),
                ('toll_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
