# Generated by Django 5.2.7 on 2025-11-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('threewheel', 'Threewheel'), ('bus', 'Bus'), ('truck', 'Truck'), ('motorbike', 'Motorbike'), ('van', 'Van')], max_length=10),
        ),
    ]
